#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iteration
#!/usr/bin/env bash
#Print using while and if
i=1

while [ "$i" -lt 11 ]; do
    echo "Best School"
    if [[ $i -eq 9 ]]; then
        echo "Hi"
    fi
    ((i++))
done
